name: Build ArtlensOptic.ro
on: 
  push:
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: public 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}